backend:
  name: git-gateway
  branch: main

media_folder: "public/uploads"
public_folder: "/uploads"

collections:
  - name: "articulos"
    label: "Artículos"
    folder: "src/content/articulos"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Título", name: "title", widget: "string" }
      - { label: "Fecha", name: "date", widget: "datetime" }
      - { label: "Autor", name: "author", widget: "string" }
      - { label: "Contenido", name: "body", widget: "markdown" }
      - { label: "Imagen", name: "image", widget: "image", required: false }
      - { label: "Etiquetas", name: "tags", widget: "list", required: false }

  - name: "paginas"
    label: "Páginas"
    folder: "src/content/paginas"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Título", name: "title", widget: "string" }
      - { label: "Contenido", name: "body", widget: "markdown" }

  # Colección de admin eliminada

  - name: "global"
    label: "Contenido Global"
    files:
      - label: "Portada"
        name: "home"
        file: "src/content/global/home.md"
        fields:
          - { label: "Título principal", name: "hero_title", widget: "string" }
          - { label: "Subtítulo", name: "hero_subtitle", widget: "string" }
          - { label: "Imagen de fondo", name: "hero_image", widget: "image", required: false }
      - label: "Footer"
        name: "footer"
        file: "src/content/global/footer.md"
        fields:
          - { label: "Texto del footer", name: "footer_text", widget: "string" }
          - { label: "Enlaces", name: "links", widget: "list", required: false }

  - name: "funciones"
    label: "Funciones/Integraciones"
    folder: "functions"
    create: true
    slug: "{{slug}}"
    extension: "js"
    format: "frontmatter"
    fields:
      - { label: "Título", name: "title", widget: "string" }
      - { label: "Código JS", name: "body", widget: "code", default_language: "javascript" }
