backend:
  name: git-gateway
  branch: main # O el nombre de la rama principal

media_folder: "public/uploads" # Carpeta donde se guardan las imágenes
public_folder: "/uploads" # Ruta pública de las imágenes

collections:
  - name: "articles"
    label: "Artículos"
    folder: "src/content/articles" # Nueva ubicación para los artículos
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "Título", name: "title", widget: "string", required: true }
      - { label: "Fecha", name: "date", widget: "datetime", format: "YYYY-MM-DD", required: true }
      - { label: "Cuerpo", name: "body", widget: "markdown", required: true }
      - { label: "Imagen Principal", name: "image", widget: "image", required: false }
      - { label: "Descripción Corta", name: "description", widget: "text", required: false }
      - { label: "Autor", name: "author", widget: "string", default: "Tu Nombre", required: false }
