backend:
  name: git-gateway
  branch: main

# Configuración correcta para Netlify Identity
site_url: https://service.hgaruna.org
display_url: https://service.hgaruna.org

media_folder: "public/uploads"
public_folder: "/uploads"

# Configuración de autenticación
publish_mode: editorial_workflow

collections:
  - name: "articles"
    label: "Artículos"
    folder: "src/content/articles"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "Título", name: "title", widget: "string" }
      - { label: "Fecha", name: "date", widget: "datetime" }
      - { label: "Autor", name: "author", widget: "string" }
      - { label: "Contenido", name: "body", widget: "markdown" }
      - { label: "Imagen", name: "image", widget: "image", required: false }
      - { label: "Etiquetas", name: "tags", widget: "list", required: false }

  - name: "paginas"
    label: "Páginas"
    folder: "src/content/paginas"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Título", name: "title", widget: "string" }
      - { label: "Contenido", name: "body", widget: "markdown" }

  - name: "funciones"
    label: "Funciones/Integraciones"
    folder: "functions"
    create: true
    slug: "{{slug}}"
    extension: "js"
    fields:
      - {
          label: "Código JS",
          name: "body",
          widget: "code",
          default_language: "javascript",
        }

  - name: "admin"
    label: "Panel de Administración"
    files:
      - label: "Configuración del Panel"
        name: "config"
        file: "src/content/admin/config.md"
        fields:
          - { label: "Título del Panel", name: "panel_title", widget: "string" }
          - { label: "Descripción", name: "panel_description", widget: "text" }
          - {
              label: "Texto de bienvenida",
              name: "welcome_text",
              widget: "markdown",
            }
          - {
              label: "Imagen de fondo",
              name: "background_image",
              widget: "image",
              required: false,
            }
          - {
              label: "Enlaces rápidos",
              name: "quick_links",
              widget: "list",
              required: false,
            }

  - name: "global"
    label: "Contenido Global"
    files:
      - label: "Portada"
        name: "home"
        file: "src/content/global/home.md"
        fields:
          - { label: "Título principal", name: "hero_title", widget: "string" }
          - { label: "Subtítulo", name: "hero_subtitle", widget: "string" }
          - {
              label: "Imagen de fondo",
              name: "hero_image",
              widget: "image",
              required: false,
            }
      - label: "Footer"
        name: "footer"
        file: "src/content/global/footer.md"
        fields:
          - { label: "Texto del footer", name: "footer_text", widget: "string" }
          - { label: "Enlaces", name: "links", widget: "list", required: false }
