backend:
  name: git-gateway
  branch: main # O el nombre de la rama principal

media_folder: "public/uploads" # Carpeta donde se guardan las imágenes
public_folder: "/uploads" # Ruta pública de las imágenes

collections:
  - name: "articles"
    label: "Artículos"
    folder: "src/content/articles" # Nueva ubicación para los artículos
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "Título del Artículo", name: "title", widget: "string", required: true }
      - { label: "Fecha", name: "date", widget: "datetime", format: "YYYY-MM-DD", required: true }
      - { label: "Cuerpo", name: "body", widget: "markdown", required: true }
      - { label: "Imagen Principal", name: "image", widget: "image", required: false }
      - { label: "Descripción Corta (para listados)", name: "description", widget: "text", required: false }
      - { label: "Autor", name: "author", widget: "string", default: "Tu Nombre", required: false }
      # Nuevos campos SEO
      - name: 'seo_metadata'
        label: 'SEO y Redes Sociales'
        widget: 'object'
        fields:
          - { label: "Título SEO (Meta Title)", name: "metaTitle", widget: "string", required: false, hint: "Título para el navegador (max 60 caracteres). Si está vacío, se usará el título del artículo." }
          - { label: "Meta Descripción", name: "metaDescription", widget: "text", required: false, hint: "Descripción para motores de búsqueda (max 160 caracteres)." }
          - { label: "Título Open Graph (OG Title)", name: "ogTitle", widget: "string", required: false, hint: "Título para compartir en redes sociales." }
          - { label: "Descripción Open Graph (OG Description)", name: "ogDescription", widget: "text", required: false, hint: "Descripción para compartir en redes sociales." }
          - { label: "Imagen Open Graph (OG Image)", name: "ogImage", widget: "image", required: false, hint: "Imagen para compartir en redes sociales (ej. 1200x630px)." }
          - { label: "Título Twitter Card", name: "twitterTitle", widget: "string", required: false, hint: "Título específico para Twitter." }
          - { label: "Descripción Twitter Card", name: "twitterDescription", widget: "text", required: false, hint: "Descripción específica para Twitter." }
          - { label: "Imagen Twitter Card", name: "twitterImage", widget: "image", required: false, hint: "Imagen específica para Twitter (ej. 1200x675px)." }
    editor:
      preview: false
    hooks:
      postPublish:
        url: "https://service.hgaruna.org/.netlify/functions/index-page"
        method: "POST"
        body: |
          {
            "url": "https://service.hgaruna.org/blog/{{year}}-{{month}}-{{day}}-{{slug}}",
            "type": "URL_UPDATED"
          }
